### ISSUE TITLE
Use .txt file extension instead of .rtf

### ISSUE THREAD

**Issue by moyogo** [kosbarts/Basic_Latin_minimum_kerning_pairs#1]
Minimum_Kerning_Basic_Latin.rtf is a plain text file and not a Rich Text Format file.
RTF files are often automatically opened by TextEdit on macOS, Word or Writer on Windows.
On macOS, double-clicking on Minimum_Kerning_Basic_Latin.rtf gives the follwoing error: `The document “Minimum_Kerning_Basic_Latin.rtf” could not be opened.`

**Comment by kosbarts** [comment]
Thanks for reporting this. I changed it to txt and downloaded the folder and the file works great on my Mac. Should be fine now.
